### ISSUE TITLE
Linear-Probing script for SSV-2

### ISSUE THREAD

**Issue by fmthoker** [XinyuSun/MME#3]
Thanks for sharing the code, I am trying to reproduce  Linear Probing results on Something-SomethingV. Can you share the setting to do so or provide the training scripts?

**Comment by XinyuSun** [comment]
Hi! We have updated our code with the linear probing script using the ssv2-400epoch-pretrained weight, see [the code here](https://github.com/XinyuSun/MME/blob/main/scripts/probing/ssv2pt-400epo.sh). The pre-trained weight is attached [here](https://drive.google.com/file/d/1aMQk3PrptvPXnGK8ZYwEAUTi5IqX71Sq/view?usp=drive_link).

Note that we reported the linear probing results with 800epoch-pretrained weight, we will release it ASAP.

**Comment by fmthoker** [comment]
Thanks for the quick response, can you make the 400epoch checkpoint  shared above public? The link you shared requires access at the moment. Also, can you mention how to run the lin prob script (GPUS, Batch size etc)

**Comment by XinyuSun** [comment]
The access to this link has been updated. We recommend using 8GPUs to run this code, and batch size can be set to larger than 24G if your GPU memory is larger than 12G. Our running command is:
`bash scripts/probing/ssv2pt-400epo.sh 8 1 0 localhost 24`
