### ISSUE TITLE
关于光流的使用

### ISSUE THREAD

**Issue by qq1332427275** [XinyuSun/MME#4]
我已经看见您已经公布了K400的光流计算结果，但未公布在HMDB51上的结果，如果我想复现论文中在HMDB51上的结果，或者其他的数据集，我需要重新计算对应数据集的光流结果吗？

**Comment by XinyuSun** [comment]
你好，我们在kinetics400数据集提取好的光流上预训练，然后将模型迁徙到不同的数据集上微调，不需要在数据集的光流上训练～
